- hosts: all
  become: True
  roles:
    - { role: base, tags: ['base'] }

- hosts: database
  become: True
  roles:
    - ufw
    - { role: mysql, tags: ['mysql'] }

- hosts: appserver
  become: True
  roles:
    - ufw
    - nginx
    - { role: webapp, tags: ['webapp'] }
