- hosts: all
  become: True
  roles:
    - { role: base, tags: ['base'] }
    - newrelic
    - fail2ban 

- hosts: database
  become: True
  roles:
    - ufw
    - { role: mysql, tags: ['mysql'] }

- hosts: appserver
  become: True
  roles:
    - ufw
    - { role: ssl, ssl_file_prefix: demo_site }
    - { role: nginx, ssl_file_prefix: demo_site }
    - { role: webapp, ssl_file_prefix: demo_site, tags: ['webapp'] }

- hosts: ldapserver
  become: True
  roles:
    - ufw
    - ldap
