---
# tasks file for finv-app
- name: Install various dependencies 
  apt: 
    name: "{{ item }}" 
  with_items:
    - python-pip
    - python-mysqldb
    - php5-mysql

- name: Remove  html directory
  file: path=/var/www/html state=absent

- name: Checkout the source code
  git:
    dest=/var/www/html
    force=yes
    repo=https://github.com/edlangley/inventory-webapp.git
    update=yes

- name: Create database
  mysql_db:
    name: "{{ database_name }}"
    login_host: "{{ hostvars[groups['database'][0]]['ansible_eth1']['ipv4']['address'] }}"
    login_user: "{{ database_user }}"
    login_password: "{{ database_password }}"
    login_port: "{{ database_port }}"
    target: "/var/www/html/sql-db-sample/electronics.sql"
    state: import

# XXX TODO investigate if this just makes a bunch of rows of the same value (probably does)
- name: Create admin user 
  shell: mysql -u {{ database_user }} -p{{ database_password }} -h {{ hostvars[groups['database'][0]]['ansible_eth1']['ipv4']['address'] }} --port={{ database_port }} --protocol=tcp {{ database_name }} -e "INSERT INTO admin_users (user_name,password) VALUES ('admin','admin');"

  # We use two template calls instead of one due to the notify
- name: Setup dbconfig
  template: src=admin-auth.php.j2 dest=/var/www/html/php/admin-auth.php owner=www-data group=www-data mode="0600"

- name: Template out nginx config
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/site.conf
  notify: reload nginx

- name: Enable the nginx site config
  file: state=link src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site.conf
  notify: reload nginx
