---
# tasks file for mysql

- name: Install MySQL server
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  become: yes
  with_items:
    - python-mysqldb
    - mysql-server

- name: Configure private bind address for database server
  template: src=my.cnf.j2  dest=/etc/mysql/my.cnf 
  notify: restart mysql

- mysql_user:
    name: "{{ database_user }}" 
    password: "{{ database_password }}" 
    encrypted: no 
    priv: '*.*:ALL'
    host: 192.168.50.4
    state: present

